name: extra_staff
description: A Banking project.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=2.13.3 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  intl: ^0.17.0 # Add this line
    
  get: ^4.1.4
  local_auth: ^1.1.6
  cupertino_icons: ^0.1.3 

  


dev_dependencies:
  flutter_test:
    sdk: flutter
  lints: ^1.0.1

flutter:

  generate: true
  uses-material-design: true

  assets:
    - lib/images/profile.png
    - lib/images/2.0x/profile.png
    - lib/images/3.0x/profile.png
